server:
  port: 0

spring:
  application:
    name: lc-user-biz

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://lc-auth:4000/oauth/token
      user-authorization-uri: http://lc-auth:4000/oauth/authorize
    resource:
      token-info-uri: http://lc-auth:4000/oauth/check_token

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://lc-eureka-node1:8761/eureka/,http://lc-eureka-node2:8762/eureka/

# Exposing Monitoring Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

#mybatis configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.group6.loyaltycard.api.user.api.entity

#Mybaatis paging plugin pagehelper settings
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true

# sql logging
logging:
  level:
    com.group6.loyaltycard.api.user.biz.mapper: DEBUG
