server:
  port: 0

spring:
  application:
    name: lc-points-biz
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

# feign
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://lc-eureka-node1:8761/eureka/,http://lc-eureka-node2:8762/eureka/

# Exposing Monitoring Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'

