server:
  port: 5002

spring:
  application:
    name: lc-points
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://lc-zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

  datasource:
    master:
      jdbc-url: jdbc:mysql://ec2-18-207-1-99.compute-1.amazonaws.com:3306/test1?useSSL=false&characterEncoding=utf8&serverTimezone=Europe/Dublin
      username: root
      password: Admin1234##
      hikari:
        maximum-pool-size: 10
        minimum-idle: 2
        max-lifetime: 1800000 # 30 minutes
        idle-timeout: 600000 # 10 minutes
        connection-timeout: 30000 # 30 seconds
        validation-timeout: 5000 # 5 seconds
        pool-name: MyHikariPool
        connection-test-query: SELECT 1
    slave:
      jdbc-url: jdbc:mysql://ec2-54-234-6-236.compute-1.amazonaws.com:3306/test1?useSSL=false&characterEncoding=utf8&serverTimezone=Europe/Dublin
      username: root
      password: Admin1234##
  mybatis:
    mapper-locations: classpath:mapper/*.xml

#  datasource:
#    master:
#      type: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://ec2-18-207-1-99.compute-1.amazonaws.com:3306/test1?characterEncoding=utf8&useSSL=false
#      username: root
#      password: Admin1234##
#    slave:
#      type: com.zaxxer.hikari.HikariDataSource
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://ec2-54-234-6-236.compute-1.amazonaws.com:3306/test1?characterEncoding=utf8&useSSL=false
#      username: root
#      password: Admin1234##


  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

# feign
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://lc-eureka-node1:8761/eureka/,http://lc-eureka-node2:8762/eureka/

# Exposing Monitoring Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'



#server:
#  port: 9002
#
#spring:
#  application:
#    name: lc-points
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1.0
#  boot:
#    admin:
#      client:
#        url: http://localhost:9004
#
#feign:
#  hystrix:
#    enabled: true
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
