server:
  port: 8888

spring:
  application:
    name: lc-config
  main:
    allow-bean-definition-overriding: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9004
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://lc-eureka-node1:8761/eureka/,http://lc-eureka-node2:8762/eureka/

