server:
  port: 8762
spring:
  application:
    name: lc-eureka
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  boot:
    admin:
      client:
        url: http://localhost:9004
eureka:
  instance:
    hostname: lc-eureka-node2
  client:
    serviceUrl:
      defaultZone: http://lc-eureka-node1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true