zuul:
  routes:
    # router name
    lc-user:
      # router address
      path: /api/user/**
      # service name
      serviceId: lc-user
    lc-transaction:
      path: /api/transaction/**
      serviceId: lc-transaction
    lc-points:
      path: /api/points/**
      serviceId: lc-points
    lc-payment:
      path: /api/payment/**
      serviceId: lc-payment

#server:
#  port: 9003
#
#spring:
#  application:
#    name: lc-gateway
#  zipkin:
#    base-url: http://localhost:9411
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#zuul:
#  routes:
#    # router name
#    lc-admin:
#      # router address
#      path: /api/admin/**
#      # service name
#      serviceId: lc-admin
#    lc-point-dev.yml:
#      path: /api/points/**
#      serviceId: lc-points