zuul:
  routes:
    lc-auth:
      path: /api/auth/**
      serviceId: lc-auth
    lc-user:
      path: /api/user/**
      serviceId: lc-user-biz
#    lc-monitor:
#      path: /api/monitor/**
#      serviceId: lc-monitor
#    lc-zipkin:
#      path: /api/zipkin/**
#      serviceId: lc-zipkin
#    lc-eureka:
#      path: /api/eureka/**
#      serviceId: lc-eureka

