spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pooki022
    url: jdbc:mysql://localhost:3306/loyaltycard?characterEncoding=utf8
    # url: jdbc:mysql://localhost:3306/lc?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai


#  jdbc:mysql://localhost:port/offers
